### ISSUE TITLE
Vague README

### ISSUE THREAD

**Issue by fkasler** [SeanWrightSec/proxy-bypass-list#1]
How do you apply this properly in Burpsuite?

**Comment by SeanWrightSec** [comment]
Apologies for the delay, You will need to configure this in your browser proxy settings. It should just be a case of coping and pasting the code into your "No proxy for" (in Firefox) or "proxy server except" (for Chrome and Edge) browsers. Alternatively if you use a browser extension such as FoxyProxy or SwitchyOmega (I'd recommend using this route), in your configuration you can copy and paste this list into the proxy bypass/ingore list.

**Comment by fkasler** [comment]
Thank you! I thought it was some hidden feature of Burpsuite that I was not seeing. I too like SwitchyOmega for Chrome.
